/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../../lib/base64";
import * as components from "../components";
import * as z from "zod";

export type GetRawMasterbrandRequest = {
    mbid: string;
};

export type GetRawMasterbrandResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Nitro response
     */
    nitro?: components.Nitro | undefined;
    body?: Uint8Array | string | undefined;
};

/** @internal */
export namespace GetRawMasterbrandRequest$ {
    export const inboundSchema: z.ZodType<GetRawMasterbrandRequest, z.ZodTypeDef, unknown> = z
        .object({
            mbid: z.string(),
        })
        .transform((v) => {
            return {
                mbid: v.mbid,
            };
        });

    export type Outbound = {
        mbid: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetRawMasterbrandRequest> = z
        .object({
            mbid: z.string(),
        })
        .transform((v) => {
            return {
                mbid: v.mbid,
            };
        });
}

/** @internal */
export namespace GetRawMasterbrandResponse$ {
    export const inboundSchema: z.ZodType<GetRawMasterbrandResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            nitro: components.Nitro$.inboundSchema.optional(),
            Body: b64$.zodInbound.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.nitro === undefined ? null : { nitro: v.nitro }),
                ...(v.Body === undefined ? null : { body: v.Body }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        nitro?: components.Nitro$.Outbound | undefined;
        Body?: Uint8Array | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetRawMasterbrandResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            nitro: components.Nitro$.outboundSchema.optional(),
            body: b64$.zodOutbound.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.nitro === undefined ? null : { nitro: v.nitro }),
                ...(v.body === undefined ? null : { Body: v.body }),
            };
        });
}
