/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../../lib/base64";
import * as components from "../components";
import * as z from "zod";

export type GetXSDResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Unexpected error
     */
    errorModel?: components.ErrorModel | undefined;
    body?: Uint8Array | string | undefined;
};

/** @internal */
export namespace GetXSDResponse$ {
    export const inboundSchema: z.ZodType<GetXSDResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            ErrorModel: components.ErrorModel$.inboundSchema.optional(),
            Body: b64$.zodInbound.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.ErrorModel === undefined ? null : { errorModel: v.ErrorModel }),
                ...(v.Body === undefined ? null : { body: v.Body }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        ErrorModel?: components.ErrorModel$.Outbound | undefined;
        Body?: Uint8Array | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetXSDResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            errorModel: components.ErrorModel$.outboundSchema.optional(),
            body: b64$.zodOutbound.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.errorModel === undefined ? null : { ErrorModel: v.errorModel }),
                ...(v.body === undefined ? null : { Body: v.body }),
            };
        });
}
