/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../../lib/base64";
import * as components from "../components";
import * as z from "zod";

export enum HasExternalId {
    True = "true",
    False = "false",
}

export type ListPeopleRequest = {
    /**
     * filter for subset of people that have an ID issued by the given authority
     */
    authority?: string | undefined;
    /**
     * filter for people who have an external identifier
     */
    hasExternalId?: Array<HasExternalId> | undefined;
    /**
     * filter for subset of people having given ID
     */
    id?: Array<string> | undefined;
    /**
     * filter for subset of people that have given an ID of the given type
     */
    idType?: string | undefined;
    /**
     * which page of results to return
     */
    page?: number | undefined;
    /**
     * number of results in each page
     */
    pageSize?: number | undefined;
    /**
     * filter for people by partner ID
     */
    partnerId?: Array<string> | undefined;
    /**
     * filter for people by partner PID
     */
    partnerPid?: Array<string> | undefined;
    /**
     * filter for subset of people having given PID
     */
    pid?: Array<string> | undefined;
    /**
     * filter for subset of people that have contributed to the given programme pid
     */
    programme?: string | undefined;
    /**
     * filter for subset of people matching supplied keyword/phrase (boolean operators permitted)
     */
    q?: string | undefined;
};

export type ListPeopleResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Nitro response
     */
    nitro?: components.Nitro | undefined;
    body?: Uint8Array | string | undefined;
    /**
     * Unexpected error
     */
    errorModel?: components.ErrorModel | undefined;
};

/** @internal */
export namespace HasExternalId$ {
    export const inboundSchema = z.nativeEnum(HasExternalId);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace ListPeopleRequest$ {
    export const inboundSchema: z.ZodType<ListPeopleRequest, z.ZodTypeDef, unknown> = z
        .object({
            authority: z.string().optional(),
            has_external_id: z.array(HasExternalId$.inboundSchema).optional(),
            id: z.array(z.string()).optional(),
            id_type: z.string().optional(),
            page: z.number().int().default(1),
            page_size: z.number().int().default(10),
            partner_id: z.array(z.string()).optional(),
            partner_pid: z.array(z.string()).optional(),
            pid: z.array(z.string()).optional(),
            programme: z.string().optional(),
            q: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.authority === undefined ? null : { authority: v.authority }),
                ...(v.has_external_id === undefined ? null : { hasExternalId: v.has_external_id }),
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.id_type === undefined ? null : { idType: v.id_type }),
                page: v.page,
                pageSize: v.page_size,
                ...(v.partner_id === undefined ? null : { partnerId: v.partner_id }),
                ...(v.partner_pid === undefined ? null : { partnerPid: v.partner_pid }),
                ...(v.pid === undefined ? null : { pid: v.pid }),
                ...(v.programme === undefined ? null : { programme: v.programme }),
                ...(v.q === undefined ? null : { q: v.q }),
            };
        });

    export type Outbound = {
        authority?: string | undefined;
        has_external_id?: Array<string> | undefined;
        id?: Array<string> | undefined;
        id_type?: string | undefined;
        page: number;
        page_size: number;
        partner_id?: Array<string> | undefined;
        partner_pid?: Array<string> | undefined;
        pid?: Array<string> | undefined;
        programme?: string | undefined;
        q?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListPeopleRequest> = z
        .object({
            authority: z.string().optional(),
            hasExternalId: z.array(HasExternalId$.outboundSchema).optional(),
            id: z.array(z.string()).optional(),
            idType: z.string().optional(),
            page: z.number().int().default(1),
            pageSize: z.number().int().default(10),
            partnerId: z.array(z.string()).optional(),
            partnerPid: z.array(z.string()).optional(),
            pid: z.array(z.string()).optional(),
            programme: z.string().optional(),
            q: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.authority === undefined ? null : { authority: v.authority }),
                ...(v.hasExternalId === undefined ? null : { has_external_id: v.hasExternalId }),
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.idType === undefined ? null : { id_type: v.idType }),
                page: v.page,
                page_size: v.pageSize,
                ...(v.partnerId === undefined ? null : { partner_id: v.partnerId }),
                ...(v.partnerPid === undefined ? null : { partner_pid: v.partnerPid }),
                ...(v.pid === undefined ? null : { pid: v.pid }),
                ...(v.programme === undefined ? null : { programme: v.programme }),
                ...(v.q === undefined ? null : { q: v.q }),
            };
        });
}

/** @internal */
export namespace ListPeopleResponse$ {
    export const inboundSchema: z.ZodType<ListPeopleResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            nitro: components.Nitro$.inboundSchema.optional(),
            Body: b64$.zodInbound.optional(),
            ErrorModel: components.ErrorModel$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.nitro === undefined ? null : { nitro: v.nitro }),
                ...(v.Body === undefined ? null : { body: v.Body }),
                ...(v.ErrorModel === undefined ? null : { errorModel: v.ErrorModel }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        nitro?: components.Nitro$.Outbound | undefined;
        Body?: Uint8Array | undefined;
        ErrorModel?: components.ErrorModel$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListPeopleResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            nitro: components.Nitro$.outboundSchema.optional(),
            body: b64$.zodOutbound.optional(),
            errorModel: components.ErrorModel$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.nitro === undefined ? null : { nitro: v.nitro }),
                ...(v.body === undefined ? null : { Body: v.body }),
                ...(v.errorModel === undefined ? null : { ErrorModel: v.errorModel }),
            };
        });
}
