/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../../lib/base64";
import * as components from "../components";
import * as z from "zod";

export type ListPipsRequest = {
    /**
     * which page of results to return
     */
    page?: number | undefined;
    /**
     * number of results in each page
     */
    pageSize?: number | undefined;
    /**
     * filter for subset of programmes matching supplied keyword/phrase (boolean operators permitted)
     */
    q?: string | undefined;
};

export type ListPipsResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Nitro response
     */
    nitro?: components.Nitro | undefined;
    body?: Uint8Array | string | undefined;
    /**
     * Unexpected error
     */
    errorModel?: components.ErrorModel | undefined;
};

/** @internal */
export namespace ListPipsRequest$ {
    export const inboundSchema: z.ZodType<ListPipsRequest, z.ZodTypeDef, unknown> = z
        .object({
            page: z.number().int().default(1),
            page_size: z.number().int().default(10),
            q: z.string().optional(),
        })
        .transform((v) => {
            return {
                page: v.page,
                pageSize: v.page_size,
                ...(v.q === undefined ? null : { q: v.q }),
            };
        });

    export type Outbound = {
        page: number;
        page_size: number;
        q?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListPipsRequest> = z
        .object({
            page: z.number().int().default(1),
            pageSize: z.number().int().default(10),
            q: z.string().optional(),
        })
        .transform((v) => {
            return {
                page: v.page,
                page_size: v.pageSize,
                ...(v.q === undefined ? null : { q: v.q }),
            };
        });
}

/** @internal */
export namespace ListPipsResponse$ {
    export const inboundSchema: z.ZodType<ListPipsResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            nitro: components.Nitro$.inboundSchema.optional(),
            Body: b64$.zodInbound.optional(),
            ErrorModel: components.ErrorModel$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.nitro === undefined ? null : { nitro: v.nitro }),
                ...(v.Body === undefined ? null : { body: v.Body }),
                ...(v.ErrorModel === undefined ? null : { errorModel: v.ErrorModel }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        nitro?: components.Nitro$.Outbound | undefined;
        Body?: Uint8Array | undefined;
        ErrorModel?: components.ErrorModel$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListPipsResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            nitro: components.Nitro$.outboundSchema.optional(),
            body: b64$.zodOutbound.optional(),
            errorModel: components.ErrorModel$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.nitro === undefined ? null : { nitro: v.nitro }),
                ...(v.body === undefined ? null : { Body: v.body }),
                ...(v.errorModel === undefined ? null : { ErrorModel: v.errorModel }),
            };
        });
}
