/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export enum AvailabilityType {
    Ondemand = "ondemand",
    Simulcast = "simulcast",
    Webcast = "webcast",
}

/** @internal */
export namespace AvailabilityType$ {
    export const inboundSchema = z.nativeEnum(AvailabilityType);
    export const outboundSchema = inboundSchema;
}
