/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export enum Embargoed {
    True = "true",
    False = "false",
}

/** @internal */
export namespace Embargoed$ {
    export const inboundSchema = z.nativeEnum(Embargoed);
    export const outboundSchema = inboundSchema;
}
