/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type Genre = {
    numberText?: string | undefined;
    id?: string | undefined;
    type?: string | undefined;
};

/** @internal */
export namespace Genre$ {
    export const inboundSchema: z.ZodType<Genre, z.ZodTypeDef, unknown> = z
        .object({
            "#text": z.string().optional(),
            id: z.string().optional(),
            type: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v["#text"] === undefined ? null : { numberText: v["#text"] }),
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.type === undefined ? null : { type: v.type }),
            };
        });

    export type Outbound = {
        "#text"?: string | undefined;
        id?: string | undefined;
        type?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Genre> = z
        .object({
            numberText: z.string().optional(),
            id: z.string().optional(),
            type: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.numberText === undefined ? null : { "#text": v.numberText }),
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.type === undefined ? null : { type: v.type }),
            };
        });
}
