/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type MediaProfileGroup = {
    numberText?: string | undefined;
    context?: string | undefined;
    pid?: string | undefined;
    platform?: string | undefined;
    territory?: string | undefined;
    transport?: string | undefined;
};

/** @internal */
export namespace MediaProfileGroup$ {
    export const inboundSchema: z.ZodType<MediaProfileGroup, z.ZodTypeDef, unknown> = z
        .object({
            "#text": z.string().optional(),
            context: z.string().optional(),
            pid: z.string().optional(),
            platform: z.string().optional(),
            territory: z.string().optional(),
            transport: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v["#text"] === undefined ? null : { numberText: v["#text"] }),
                ...(v.context === undefined ? null : { context: v.context }),
                ...(v.pid === undefined ? null : { pid: v.pid }),
                ...(v.platform === undefined ? null : { platform: v.platform }),
                ...(v.territory === undefined ? null : { territory: v.territory }),
                ...(v.transport === undefined ? null : { transport: v.transport }),
            };
        });

    export type Outbound = {
        "#text"?: string | undefined;
        context?: string | undefined;
        pid?: string | undefined;
        platform?: string | undefined;
        territory?: string | undefined;
        transport?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, MediaProfileGroup> = z
        .object({
            numberText: z.string().optional(),
            context: z.string().optional(),
            pid: z.string().optional(),
            platform: z.string().optional(),
            territory: z.string().optional(),
            transport: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.numberText === undefined ? null : { "#text": v.numberText }),
                ...(v.context === undefined ? null : { context: v.context }),
                ...(v.pid === undefined ? null : { pid: v.pid }),
                ...(v.platform === undefined ? null : { platform: v.platform }),
                ...(v.territory === undefined ? null : { territory: v.territory }),
                ...(v.transport === undefined ? null : { transport: v.transport }),
            };
        });
}
