/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Mixin, Mixin$ } from "./mixin";
import { UnstableMixins, UnstableMixins$ } from "./unstablemixins";
import * as z from "zod";

export type Mixins = {
    mixin?: Array<Mixin> | undefined;
    unstableMixins?: UnstableMixins | undefined;
};

/** @internal */
export namespace Mixins$ {
    export const inboundSchema: z.ZodType<Mixins, z.ZodTypeDef, unknown> = z
        .object({
            mixin: z.array(Mixin$.inboundSchema).optional(),
            unstable_mixins: UnstableMixins$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.mixin === undefined ? null : { mixin: v.mixin }),
                ...(v.unstable_mixins === undefined ? null : { unstableMixins: v.unstable_mixins }),
            };
        });

    export type Outbound = {
        mixin?: Array<Mixin$.Outbound> | undefined;
        unstable_mixins?: UnstableMixins$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Mixins> = z
        .object({
            mixin: z.array(Mixin$.outboundSchema).optional(),
            unstableMixins: UnstableMixins$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.mixin === undefined ? null : { mixin: v.mixin }),
                ...(v.unstableMixins === undefined ? null : { unstable_mixins: v.unstableMixins }),
            };
        });
}
