/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type PublishedTime = {
    end?: Date | undefined;
    start?: Date | undefined;
    duration?: string | undefined;
    additionalProperties: { [k: string]: any };
};

/** @internal */
export namespace PublishedTime$ {
    export const inboundSchema: z.ZodType<PublishedTime, z.ZodTypeDef, unknown> = z
        .object({
            end: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
            start: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
            duration: z.string().optional(),
        })
        .catchall(z.any())
        .transform((v) => {
            const { end, start, duration, ...additionalProperties } = v;

            return {
                ...(v.end === undefined ? null : { end: v.end }),
                ...(v.start === undefined ? null : { start: v.start }),
                ...(v.duration === undefined ? null : { duration: v.duration }),
                additionalProperties,
            };
        });

    export type Outbound = {
        end?: string | undefined;
        start?: string | undefined;
        duration?: string | undefined;
        [additionalProperties: string]: unknown;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PublishedTime> = z
        .object({
            end: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
            start: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
            duration: z.string().optional(),
            additionalProperties: z.record(z.any()),
        })
        .transform((v) => {
            return {
                ...v.additionalProperties,
                ...(v.end === undefined ? null : { end: v.end }),
                ...(v.start === undefined ? null : { start: v.start }),
                ...(v.duration === undefined ? null : { duration: v.duration }),
            };
        });
}
