/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type TxTime = {
    creditsShowing?: Date | undefined;
    end?: Date | undefined;
    start?: Date | undefined;
};

/** @internal */
export namespace TxTime$ {
    export const inboundSchema: z.ZodType<TxTime, z.ZodTypeDef, unknown> = z
        .object({
            credits_showing: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
            end: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
            start: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
        })
        .transform((v) => {
            return {
                ...(v.credits_showing === undefined ? null : { creditsShowing: v.credits_showing }),
                ...(v.end === undefined ? null : { end: v.end }),
                ...(v.start === undefined ? null : { start: v.start }),
            };
        });

    export type Outbound = {
        credits_showing?: string | undefined;
        end?: string | undefined;
        start?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, TxTime> = z
        .object({
            creditsShowing: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
            end: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
            start: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
        })
        .transform((v) => {
            return {
                ...(v.creditsShowing === undefined ? null : { credits_showing: v.creditsShowing }),
                ...(v.end === undefined ? null : { end: v.end }),
                ...(v.start === undefined ? null : { start: v.start }),
            };
        });
}
