/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Sort, Sort$ } from "./sort";
import * as z from "zod";

export type UnstableSorts = {
    sort?: Array<Sort> | undefined;
};

/** @internal */
export namespace UnstableSorts$ {
    export const inboundSchema: z.ZodType<UnstableSorts, z.ZodTypeDef, unknown> = z
        .object({
            sort: z.array(Sort$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.sort === undefined ? null : { sort: v.sort }),
            };
        });

    export type Outbound = {
        sort?: Array<Sort$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UnstableSorts> = z
        .object({
            sort: z.array(Sort$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.sort === undefined ? null : { sort: v.sort }),
            };
        });
}
