/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type WarningItemsWarningWarning = {
    numberText?: string | undefined;
    shortDescription?: string | undefined;
    warningCode?: string | undefined;
};

export type WarningItemsWarning = {
    numberText?: string | undefined;
    shortDescription?: string | undefined;
    warning?: Array<WarningItemsWarningWarning> | undefined;
    warningCode?: string | undefined;
};

export type WarningItems = {
    warning?: Array<WarningItemsWarning> | undefined;
};

/** @internal */
export namespace WarningItemsWarningWarning$ {
    export const inboundSchema: z.ZodType<WarningItemsWarningWarning, z.ZodTypeDef, unknown> = z
        .object({
            "#text": z.string().optional(),
            short_description: z.string().optional(),
            warning_code: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v["#text"] === undefined ? null : { numberText: v["#text"] }),
                ...(v.short_description === undefined
                    ? null
                    : { shortDescription: v.short_description }),
                ...(v.warning_code === undefined ? null : { warningCode: v.warning_code }),
            };
        });

    export type Outbound = {
        "#text"?: string | undefined;
        short_description?: string | undefined;
        warning_code?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WarningItemsWarningWarning> = z
        .object({
            numberText: z.string().optional(),
            shortDescription: z.string().optional(),
            warningCode: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.numberText === undefined ? null : { "#text": v.numberText }),
                ...(v.shortDescription === undefined
                    ? null
                    : { short_description: v.shortDescription }),
                ...(v.warningCode === undefined ? null : { warning_code: v.warningCode }),
            };
        });
}

/** @internal */
export namespace WarningItemsWarning$ {
    export const inboundSchema: z.ZodType<WarningItemsWarning, z.ZodTypeDef, unknown> = z
        .object({
            "#text": z.string().optional(),
            short_description: z.string().optional(),
            warning: z.array(z.lazy(() => WarningItemsWarningWarning$.inboundSchema)).optional(),
            warning_code: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v["#text"] === undefined ? null : { numberText: v["#text"] }),
                ...(v.short_description === undefined
                    ? null
                    : { shortDescription: v.short_description }),
                ...(v.warning === undefined ? null : { warning: v.warning }),
                ...(v.warning_code === undefined ? null : { warningCode: v.warning_code }),
            };
        });

    export type Outbound = {
        "#text"?: string | undefined;
        short_description?: string | undefined;
        warning?: Array<WarningItemsWarningWarning$.Outbound> | undefined;
        warning_code?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WarningItemsWarning> = z
        .object({
            numberText: z.string().optional(),
            shortDescription: z.string().optional(),
            warning: z.array(z.lazy(() => WarningItemsWarningWarning$.outboundSchema)).optional(),
            warningCode: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.numberText === undefined ? null : { "#text": v.numberText }),
                ...(v.shortDescription === undefined
                    ? null
                    : { short_description: v.shortDescription }),
                ...(v.warning === undefined ? null : { warning: v.warning }),
                ...(v.warningCode === undefined ? null : { warning_code: v.warningCode }),
            };
        });
}

/** @internal */
export namespace WarningItems$ {
    export const inboundSchema: z.ZodType<WarningItems, z.ZodTypeDef, unknown> = z
        .object({
            warning: z.array(z.lazy(() => WarningItemsWarning$.inboundSchema)).optional(),
        })
        .transform((v) => {
            return {
                ...(v.warning === undefined ? null : { warning: v.warning }),
            };
        });

    export type Outbound = {
        warning?: Array<WarningItemsWarning$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WarningItems> = z
        .object({
            warning: z.array(z.lazy(() => WarningItemsWarning$.outboundSchema)).optional(),
        })
        .transform((v) => {
            return {
                ...(v.warning === undefined ? null : { warning: v.warning }),
            };
        });
}
